# Environment for Alice TRF analysis
# usage: $ conda env create --file=environment.yml
name: eelbrain
channels:
- conda-forge
dependencies:
- eelbrain >= 0.39.10
- pip
- ipython
- jupyter
- ipywidgets
- jupytext
- seaborn
- pip:
  - gammatone
  - https://github.com/christianbrodbeck/TRF-Tools/archive/refs/heads/main.zip
